language: node_js
node_js:
- 4.2.1
before_script:
- npm install -g bower
- npm install
- bower install
notifications:
  hipchat:
    rooms:
      secure: aPWiw16E00siOPsVF++BQp2Ee4Yrzz/crxz/J2gMziiaGNbgWRzpKU8fKcgrdTbeivFc6wHFFEhe86QQTh8xB32CYVDKIW/WDzXgYvwn9fH68JPoskAbeAIFww6EYbbt6w1gWTRAHL9C2mhZ5xw7d9399NOFa2WNHwSZJ3omh92MUpbMqKt+VXwUz8b76CkWDVESKTNOe2/WcgGxhjMBDPHNIrj9MSbem1hWz10/5AS2MTQMJfNcVXk8dXGzK0wORpvBNQ6u8S3Bpu4Q58hK7MK1d77aiyARo7IRakw4MZAYnwHO40oBiU8UEDjcGrdoj0oGqAseuCDORc6fRKDrlDV4lDaH76fy86DFI8lBRLAXvrWFmQWqSkmS3eLf4GP/JYuST0O2PyzpeOITmGSUmeje5/skRb8jNo0/NXHUcDtiuktlkriZ/CUTVsxNMOEajGPiPlPLA8MHG/OKPsOiMFsT6GwnX90GsEONsvT+tWiB3YpAu0eFZ0zovO92gZM3jRP1zRxGT3EP0iP7bsvyxUvsCxekCcQW1XFRw3T2XoK8QKWDiwG+R3Nezk/phWEpH5KxZ+42a87DRR+LCKRwtayl+62foRG9r+kRt37JEPd4F0yN+4X0L/QTRqM8gvE7MB01nsAFSwBbcbsMS8QMzl1Oh87brzhgXrcp4SjF0qU=
